apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-worker-deployment
spec:
  selector:
    matchLabels:
      app: ocr-worker
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: ocr-worker
    spec:
      containers:
        - name: ocr-worker
          image: ocr-worker:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: BROKER_INCOMING_TASKS
              value: pending_tasks
            - name: BROKER_OUTGOING_TASKS
              value: done_tasks
            - name: BROKER_URL
              value: message-broker
            - name: BROKER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: message-broker-default-user
                  key: username
            - name: BROKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: message-broker-default-user
                  key: password