apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: ocr-worker:1.3
        ports:
        - containerPort: 80
        imagePullPolicy: Never        
        env:
          - name: RABBIT_HOST
            value: "message-broker"
          - name: RABBIT_USERNAME
            valueFrom:
              secretKeyRef:
                name: message-broker-default-user
                key: username
          - name: RABBIT_PWD
            valueFrom:
              secretKeyRef:
                name: message-broker-default-user
                key: password 
          - name: PENDING_TASKS_BINDING
            value: pending-tasks
          - name: DONE_TASKS_BINDING
            value: done-tasks
      terminationGracePeriodSeconds: 10